// Lokale FAQ-Datenbank des KI-Buddys — beantwortet häufige Fragen ohne API.
//
// Geteilt von Frontend (Sofort- und Offline-Antworten, über src/lib/buddyFaq.js)
// und Backend (die zur Frage passenden Einträge landen als geprüftes Wissen im
// LLM-Prompt). Liegt deshalb unter backend/: das Backend-Image kopiert nur
// diesen Ordner, der Frontend-Build sieht dagegen das ganze Repo.
//
// Aufbau eines Eintrags:
//   id        eindeutiger, stabiler Schlüssel
//   category  Themengruppe (siehe FAQ_CATEGORIES)
//   question  kanonische Frage (Anzeige + Prompt-Kontext)
//   all       Begriffsgruppen — aus JEDER Gruppe muss mindestens ein Begriff in
//             der Frage vorkommen. Mehr Gruppen = spezifischerer Eintrag, der
//             bei einem Treffer allgemeinere Einträge schlägt.
//   any       optionale Zusatzbegriffe; erhöhen Punktzahl und Abdeckung
//   answer    Antworttext oder Liste von Varianten (Smalltalk rotiert)
//   page      optional: passende App-Seite (Routen-Key aus pages.config.js)
//
// Begriffe werden normalisiert verglichen (klein, ä→ae, ö→oe, ü→ue, ß→ss).
// Ein Begriff trifft ein Wort, wenn das Wort mit ihm beginnt (Begriffe ab
// 3 Zeichen) oder ihn enthält (ab 5 Zeichen) — "hecht" trifft also auch
// "hechte" und "hechtangeln". Begriffe mit Leerzeichen sind Phrasen.
//
// Fachlich konsistent zu FISHING_KNOWLEDGE in buddyKnowledge.js halten.
// Gesetzliche Details (Schonzeiten, Mindestmaße) sind je Bundesland
// verschieden — hier nur allgemein, konkrete Werte liefert der Regel-Assistent.

export const FAQ_CATEGORIES = {
  smalltalk: 'Smalltalk',
  app: 'App-Funktionen',
  einstieg: 'Einstieg & Regeln',
  fischarten: 'Fischarten',
  koeder: 'Köder',
  montagen: 'Montagen',
  knoten: 'Knoten',
  ausruestung: 'Ausrüstung',
  technik: 'Technik & Drill',
  bedingungen: 'Wetter & Bedingungen',
  jahreszeit: 'Jahreszeiten',
  gewaesser: 'Gewässer & Spots',
  handling: 'Fischbehandlung',
  sicherheit: 'Sicherheit',
  probleme: 'Wenn es nicht läuft',
};

export const FAQ_ENTRIES = [
  // ---------------------------------------------------------------- Smalltalk
  {
    id: 'begruessung',
    category: 'smalltalk',
    question: 'Hallo!',
    all: [['hallo', 'hi$', 'hey', 'moin', 'servus', 'guten morgen', 'guten tag', 'guten abend', 'gruess', 'gruss gott', 'na du']],
    answer: [
      'Hey, schön, dass du da bist! Worum geht es heute — Zielfisch, Köder oder ein neuer Spot?',
      'Moin! Petri Heil schon mal vorab. Was hast du vor: Trip planen, Köderfrage oder einfach ein bisschen fachsimpeln?',
      'Hallo! Ich bin startklar. Erzähl mal, wo willst du als Nächstes ans Wasser?',
    ],
  },
  {
    id: 'danke',
    category: 'smalltalk',
    question: 'Danke!',
    all: [['danke', 'dankeschoen', 'vielen dank', 'merci', 'besten dank']],
    answer: [
      'Gern geschehen! Wenn du vom Wasser zurück bist, erzähl mir, wie es gelaufen ist.',
      'Immer gern. Petri Heil — und denk dran: Ein Fang ist schnell im Fangbuch, sag einfach Bescheid.',
      'Dafür bin ich da. Meld dich, wenn du noch etwas brauchst!',
    ],
  },
  {
    id: 'petri-heil',
    category: 'smalltalk',
    question: 'Petri Heil!',
    all: [['petri']],
    any: ['heil', 'dank'],
    answer: [
      'Petri Dank! Wo geht es hin und auf welchen Fisch willst du es versuchen?',
      'Petri Dank! Ich drück dir die Daumen, dass die Schnur heute öfter zuckt als sonst.',
    ],
  },
  {
    id: 'wer-bist-du',
    category: 'smalltalk',
    question: 'Wer bist du?',
    all: [['wer bist du', 'was bist du', 'stell dich vor', 'wie heisst du', 'bist du eine ki', 'bist du ein mensch']],
    answer: 'Ich bin dein KI-Buddy in BaitBuddy — ein Angel-Kumpel, der dir bei Ködern, Montagen, Technik, Wetter, Spots und Regeln hilft. Häufige Fragen beantworte ich sofort aus meinem eingebauten Wissen, auch ohne Internet. Für alles Persönliche, etwa Tipps zu deinen letzten Fängen oder dem Wetter an deinem Standort, frage ich online nach. Ich bin eine KI, kein Mensch — aber ich höre gern zu, wenn du vom Wasser erzählst.',
  },
  {
    id: 'was-kannst-du',
    category: 'smalltalk',
    question: 'Was kannst du alles?',
    all: [['was kannst du', 'was kann ich dich fragen', 'wobei hilfst du', 'wie kannst du mir helfen', 'was machst du', 'wofuer bist du']],
    answer: 'Eine ganze Menge! Ich erkläre dir Köderführung, Montagen und Knoten Schritt für Schritt, sage dir, wie Wetter, Luftdruck und Jahreszeit das Beißverhalten beeinflussen, und helfe dir, gute Spots zu erkennen. Online kann ich außerdem Fänge ins Fangbuch eintragen ("Trag einen Karpfen in mein Fangbuch ein"), Spots speichern, Seiten der App öffnen und Tipps passend zu deinen Fängen und deinem Standort geben. Womit fangen wir an?',
  },

  // ---------------------------------------------------------- App-Funktionen
  {
    id: 'app-fangbuch',
    category: 'app',
    question: 'Wie funktioniert das Fangbuch?',
    all: [['fangbuch', 'logbuch', 'fang eintragen', 'fang speichern', 'fang notieren', 'faenge eintragen']],
    any: ['funktion', 'eintrag', 'speicher', 'nutz', 'benutz', 'foto'],
    answer: 'Im Fangbuch hältst du jeden Fang fest: Fischart, Länge, Gewicht, Köder, Spot, Notizen und Foto. Am schnellsten geht es über mich — sag einfach "Trag einen Barsch in mein Fangbuch ein", dann lege ich den Eintrag an, und die Details ergänzt du später. Lädst du ein Fangfoto hoch, bestimmt die KI-Fotoerkennung die Fischart und schätzt Länge und Gewicht. Aus deinen Einträgen entstehen Statistiken und meine persönlichen Tipps für dich.',
    page: 'Logbook',
  },
  {
    id: 'app-spots-karte',
    category: 'app',
    question: 'Wie speichere ich einen Spot auf der Karte?',
    all: [['spot', 'angelplatz', 'angelstelle', 'karte', 'platz'], ['speicher', 'markier', 'anleg', 'merken', 'karte', 'eintragen']],
    answer: 'Auf der Karte siehst du deine Spots als Marker und kannst neue Plätze anlegen, mit Gewässertyp und Notizen. Noch schneller geht es über mich: "Speichere diesen Spot als See" — dann lege ich den Platz an deinem aktuellen Standort an (See, Fluss, Teich, Kanal oder Bach). Tipp: Notier dir zu jedem Spot Tiefe, Struktur und was dort gebissen hat, das macht deine Auswertungen später viel wertvoller.',
    page: 'Map',
  },
  {
    id: 'app-offline',
    category: 'app',
    question: 'Funktioniert die App ohne Internet?',
    all: [['offline', 'ohne internet', 'ohne netz', 'kein netz', 'kein empfang', 'funkloch', 'kein internet']],
    answer: 'Teilweise, ja. Häufige Angelfragen beantworte ich auch ohne Netz aus meinem eingebauten Wissen — Köder, Montagen, Knoten, Fischarten, Wetter-Grundlagen und Regeln. Mit dem Offline-Angelpack lädst du dir vorher Spots, dein Fangbuch und die Schonzeiten aufs Gerät, damit du sie am Wasser auch im Funkloch hast. Persönliche Auswertungen, Live-Wetter und das Eintragen per Zuruf brauchen dagegen eine Verbindung.',
    page: 'OfflineFishingPack',
  },
  {
    id: 'app-koeder3d',
    category: 'app',
    question: 'Kann ich mir die Köderführung ansehen?',
    all: [['koederanimation', 'laufverhalten', '3d', 'animation', 'koederfuehrung ansehen']],
    answer: 'Ja! In der 3D-Köderführung siehst du Wobbler, Gummifisch am Jigkopf, Spinner, Blinker und Oberflächenköder mit echtem Laufverhalten. Du kannst die Führungsstile live umschalten — Jiggen, Faulenzen, Stop-and-Go, Twitchen und Walk the Dog —, das Tempo regeln und die Kamera frei drehen. So siehst du genau, was dein Köder unter Wasser macht, wenn du an der Rolle drehst.',
    page: 'Koeder3D',
  },
  {
    id: 'app-premium',
    category: 'app',
    question: 'Was bringt Premium und wie kündige ich?',
    all: [['premium', 'abo', 'abonnement', 'ultimate', 'upgrade', 'kuendig', 'tarif']],
    answer: 'Die aktuellen Pläne mit Preisen und Funktionsumfang findest du unter "Tarif & KI-Zugriff" — dort siehst du auch, welcher Plan gerade aktiv ist und bis wann. Kaufst du in der Android-App, läuft das über Google Play: Abos verwaltest und kündigst du dort unter "Zahlungen und Abos". Ein Kauf im Browser ist eine Einmalzahlung für einen festen Zeitraum und verlängert sich nicht automatisch.',
    page: 'PremiumPlans',
  },
  {
    id: 'app-daten',
    category: 'app',
    question: 'Was weißt du über mich?',
    all: [['was weisst du ueber mich', 'was weisst du von mir', 'meine daten', 'datenschutz', 'was speicherst du']],
    answer: 'Das zeige ich dir ganz offen auf der Seite "BaitBuddy kennt dich": deine gespeicherten Zielfische, Methoden, Gewässertypen, Erfahrung, Region, Ziele, bekannte Ausrüstung und Touren sowie die Muster, die ich aus deinem Fangbuch ableite. Jede Angabe kannst du dort korrigieren oder löschen. Stimmt etwas nicht, sag es mir einfach — lieber einmal richtiggestellt als dauerhaft falsch angenommen.',
    page: 'BuddyKnowsYou',
  },

  // -------------------------------------------------------- Einstieg & Regeln
  {
    id: 'anfaenger',
    category: 'einstieg',
    question: 'Wie fange ich mit dem Angeln an?',
    all: [['anfaenger', 'einsteiger', 'anfangen', 'einstieg', 'fange ich mit dem angeln an', 'wie fange ich an', 'womit fange ich an', 'neu beim angeln', 'angeln lernen', 'erstes mal', 'erste mal', 'noch nie geangelt']],
    answer: 'Super, dass du einsteigst! So gehst du es am besten an: 1. Kläre die Papiere — in Deutschland brauchst du meist einen Fischereischein und zusätzlich eine Erlaubnis für das Gewässer (Gewässerkarte). 2. Starte mit einer einfachen Posen- oder Grundmontage auf Friedfische wie Rotauge oder Brasse, Köder Made oder Wurm — da gibt es schnell Bisse. 3. Als Gerät reicht eine 3–3,6 m lange Allround- oder Feederrute mit 2500er-Rolle und 0,20–0,22 mm Monoschnur. 4. Lerne zwei Knoten sicher: Clinch und Palomar. 5. Pack Kescher, Hakenlöser und Maßband ein. Welche Gewässer hast du in deiner Nähe?',
  },
  {
    id: 'angelschein',
    category: 'einstieg',
    question: 'Brauche ich einen Angelschein?',
    all: [['angelschein', 'fischereischein', 'fischerpruefung', 'angelpruefung', 'angellizenz', 'fischerschein']],
    any: ['brauch', 'mach', 'bekomm', 'pruefung', 'kurs', 'kost'],
    answer: 'In Deutschland brauchst du zum Angeln in der Regel einen Fischereischein. Dafür machst du einen Vorbereitungskurs und legst die staatliche Prüfung ab — geprüft werden Fischkunde, Gewässerkunde, Gerätekunde, Gesetzeskunde und Tierschutz. Zuständig ist dein Bundesland; einige Länder haben Ausnahmen wie zeitlich begrenzte Urlauber- oder Touristenscheine. Zusätzlich brauchst du für jedes Gewässer eine Erlaubnis vom Pächter oder Verein. Im Quiz kannst du Prüfungsfragen üben, und ich frage dich auch gern direkt ab.',
    page: 'Quiz',
  },
  {
    id: 'gewaesserkarte',
    category: 'einstieg',
    question: 'Was ist eine Gewässerkarte?',
    all: [['gewaesserkarte', 'erlaubnisschein', 'tageskarte', 'angelkarte', 'jahreskarte', 'wochenkarte']],
    answer: 'Die Gewässerkarte (Erlaubnisschein) ist die Angelerlaubnis für ein bestimmtes Gewässer — zusätzlich zu deinem Fischereischein. Du bekommst sie beim Verein, Pächter, in Angelläden oder online, als Tages-, Wochen- oder Jahreskarte. Lies die Gewässerordnung darauf genau: Dort stehen erlaubte Ruten, Köder, Angelzeiten, Nachtangel-Regeln, Entnahmelimits und oft strengere Mindestmaße als im Landesgesetz.',
  },
  {
    id: 'schonzeit',
    category: 'einstieg',
    question: 'Wie finde ich Schonzeiten und Mindestmaße heraus?',
    all: [['schonzeit', 'schonmass', 'mindestmass', 'fangverbot', 'laichschonzeit', 'entnahmefenster']],
    answer: 'Schonzeiten und Mindestmaße legt jedes Bundesland in seiner Fischereiverordnung fest, und Vereine oder Pächter verschärfen sie oft in der Gewässerordnung. Grob gilt: Die Schonzeit liegt um die Laichzeit — bei Hecht und Zander meist im Frühjahr, bei Bachforelle im Herbst und Winter. Die konkreten Daten für dein Bundesland und deine Fischart zeigt dir der Regel-Assistent, der auch eine gemessene Länge gegen das Mindestmaß prüft. Ein Fisch in der Schonzeit oder unter Mindestmaß geht immer sofort und schonend zurück.',
    page: 'RuleAssistant',
  },
  {
    id: 'nachtangeln',
    category: 'einstieg',
    question: 'Was muss ich beim Nachtangeln beachten?',
    all: [['nachtangeln', 'nachts angeln', 'in der nacht', 'nachtansitz', 'bei dunkelheit', 'im dunkeln']],
    answer: 'Prüf zuerst, ob Nachtangeln am Gewässer erlaubt ist — das regeln Landesrecht und Gewässerordnung sehr unterschiedlich. Praktisch: Richte deinen Platz noch bei Tageslicht ein, lege Kescher, Abhakmatte und Zange griffbereit und markiere die Rutenspitzen oder Posen mit Knicklichtern. Elektronische Bissanzeiger helfen beim Grundangeln. Nutze eine Kopflampe mit Rotlicht, damit du die Fische nicht verscheuchst und nicht geblendet wirst. Aal, Zander und Wels sind die klassischen Nachtfische.',
  },
  {
    id: 'catch-and-release',
    category: 'einstieg',
    question: 'Darf ich Fische zurücksetzen?',
    all: [['zuruecksetz', 'catch and release', 'release', 'freilassen', 'zurueck ins wasser', 'wieder reinsetzen']],
    answer: 'Fische unter Mindestmaß, in der Schonzeit oder geschützte Arten musst du sofort und schonend zurücksetzen. Beim gezielten Fangen und Zurücksetzen maßiger Fische ist die Lage in Deutschland heikel: Nach dem Tierschutzrecht brauchst du für das Angeln einen vernünftigen Grund, in der Regel die Verwertung. Einige Gewässerordnungen schreiben die Entnahme bestimmter Fische sogar vor. Wenn du zurücksetzt: Fisch möglichst im Wasser abhaken, nur mit nassen Händen anfassen und im Wasser stützen, bis er selbst wegschwimmt.',
  },

  // -------------------------------------------------------------- Fischarten
  {
    id: 'hecht',
    category: 'fischarten',
    question: 'Wie fange ich einen Hecht?',
    all: [['hecht']],
    any: ['wo', 'wann', 'fang', 'tipp', 'stand', 'zeit', 'beisst', 'angel'],
    answer: 'Hechte sind Lauerjäger: Sie stehen an Krautkanten, vor Schilfgürteln, an Seerosenfeldern und über Barschbergen. Die besten Monate sind nach der Schonzeit im späten Frühjahr und vor allem der Herbst, wenn sie sich Winterspeck anfressen; bei Bewölkung und Wind beißen sie oft den ganzen Tag. Bewährt sind Gummifische von 10–20 cm am 10–30 g Jigkopf, Wobbler, große Spinner und tote Köderfische. Ganz wichtig: immer ein Stahl- oder mindestens 0,80 mm dickes Fluorocarbon-Vorfach, sonst beißt er dir die Schnur durch.',
  },
  {
    id: 'hecht-koeder',
    category: 'fischarten',
    question: 'Welcher Köder ist gut für Hecht?',
    all: [['hecht'], ['koeder', 'gummifisch', 'wobbler', 'spinner', 'blinker', 'jerkbait', 'womit', 'kunstkoeder', 'koederfisch']],
    answer: 'Für Hecht haben sich drei Köder bewährt: Gummifische von 10–20 cm am 10–30 g Jigkopf, gejiggt oder langsam durchgekurbelt; Wobbler und Jerkbaits von 10–15 cm, getwitcht mit Pausen, denn die Pause bringt den Biss; und große Spinner (Größe 4–5), die gleichmäßig über Krautfeldern laufen. Im kalten Wasser sind langsame Köder und tote Köderfische an der Pose stark. Bei trübem Wasser greif zu grellen Farben wie Firetiger, bei klarem zu natürlichen Dekoren. Und nie ohne Stahl- oder dickes Fluorocarbon-Vorfach!',
    page: 'Koeder3D',
  },
  {
    id: 'zander',
    category: 'fischarten',
    question: 'Wie fange ich einen Zander?',
    all: [['zander']],
    any: ['wo', 'wann', 'fang', 'tipp', 'stand', 'zeit', 'beisst', 'nacht', 'angel'],
    answer: 'Zander jagen in der Dämmerung und nachts, besonders gern bei trübem Wasser. Du findest sie über hartem Grund, an Kanten, in Löchern, an Steinpackungen, Brückenpfeilern und Hafeneinfahrten; im Sommer ziehen sie nachts ins Flache, im Winter stehen sie tief. Klassiker sind Gummifische von 8–12 cm am 5–14 g Jigkopf, gejiggt oder gefaulenzt, oder ein kleiner toter Köderfisch von 6–10 cm am Einzelhaken. Der Biss kommt meist in der Absinkphase — zuckt die Schnur, sofort kräftig anschlagen, denn das Zandermaul ist hart.',
  },
  {
    id: 'zander-koeder',
    category: 'fischarten',
    question: 'Welcher Köder ist gut für Zander?',
    all: [['zander'], ['koeder', 'gummifisch', 'wobbler', 'jig', 'womit', 'kunstkoeder', 'koederfisch', 'koefi']],
    answer: 'Nummer eins für Zander ist der schlanke Gummifisch oder No-Action-Shad von 8–12 cm am 5–14 g Jigkopf — so schwer, dass er nach jedem Sprung 2–4 Sekunden bis zum Grund braucht. Führ ihn gejiggt oder gefaulenzt knapp über Grund. Nachts laufen flach geführte schlanke Wobbler an der Uferkante sehr gut. Beim Ansitz ist ein toter Köderfisch von 6–10 cm (Rotauge, Barsch, Grundel) am Einzelhaken ideal; hier früh anschlagen. Farben: bei trübem Wasser hell oder grell, bei klarem natürlich.',
    page: 'Koeder3D',
  },
  {
    id: 'barsch',
    category: 'fischarten',
    question: 'Wie fange ich Barsche?',
    all: [['barsch']],
    any: ['wo', 'wann', 'fang', 'tipp', 'stand', 'zeit', 'koeder', 'beisst', 'angel', 'womit'],
    answer: 'Barsche sind tagaktive Schwarmjäger: Wo einer beißt, stehen meist mehrere. Such sie an Stegen, Steinpackungen, versunkenen Bäumen, Krautkanten und Barschbergen, und achte auf jagende Fische an der Oberfläche. Kleine Köder funktionieren am besten: Gummifische von 5–8 cm am 3–7 g Jigkopf, Spinner Größe 1–3, kleine Wobbler oder die Drop-Shot-Montage für träge Fische. Dazu passt eine leichte Spinnrute mit dünner geflochtener Schnur (0,06–0,10 mm) und Fluorocarbon-Vorfach.',
  },
  {
    id: 'forelle',
    category: 'fischarten',
    question: 'Wie fange ich Forellen?',
    all: [['forelle', 'regenbogner', 'saibling']],
    any: ['wo', 'wann', 'fang', 'tipp', 'koeder', 'teich', 'bach', 'womit', 'angel', 'beisst'],
    answer: 'Das hängt vom Gewässer ab. Im Forellenteig (Put and Take) fängst du am besten mit Forellenteig oder Bienenmaden am Sbirolino oder an der Tremarella-Montage, sehr langsam eingeholt mit zitternder Rutenspitze, Vorfach 0,16–0,20 mm. Im Bach oder Fluss stehen Forellen strömungsgeschützt hinter Steinen, unter Uferkanten und am Beginn von Gumpen; dort fischst du mit kleinen Spinnern (Größe 0–2), Mini-Wobblern von 3–5 cm oder Wurm, gegen die Strömung geworfen. Forellen lieben kühles, sauerstoffreiches Wasser — morgens und abends sind sie am aktivsten.',
  },
  {
    id: 'karpfen',
    category: 'fischarten',
    question: 'Wie fange ich einen Karpfen?',
    all: [['karpf', 'karpfen']],
    any: ['wo', 'wann', 'fang', 'tipp', 'stand', 'zeit', 'beisst', 'angel'],
    answer: 'Karpfen sind vorsichtige Friedfische, die viel Ruhe und einen gut vorbereiteten Platz belohnen. Such Stellen mit Nahrung: Krautkanten, Seerosen, flache Buchten, Muschelbänke und die windzugewandte Seite. Bewährt ist die Haarmontage mit Boilie oder Mais auf 60–100 g Festblei, die für den Selbsthakeffekt sorgt. Füttere den Spot vorher gezielt an und lege die Wurfweite per Schnurclip fest. Aktiv sind Karpfen ab etwa 12 °C Wassertemperatur, besonders in Dämmerung und Nacht; Luftblasen und aufgewühltes Wasser verraten fressende Fische.',
  },
  {
    id: 'karpfen-koeder',
    category: 'fischarten',
    question: 'Welcher Köder ist gut für Karpfen?',
    all: [['karpf', 'karpfen'], ['koeder', 'boilie', 'mais', 'pellet', 'futter', 'womit', 'tigernuss', 'teig']],
    answer: 'Die Klassiker für Karpfen sind Boilies von 15–20 mm, Dosen- oder Partikelmais, Pellets und Tigernüsse, jeweils an der Haarmontage. Mais und Pellets bringen schnelle Bisse, auch von kleineren Karpfen; größere Boilies sortieren kleine Fische aus. Ein Pop-up, also ein auftreibender Boilie, hilft über weichem Schlamm oder leichtem Kraut. Füttere denselben Köder in kleinen Mengen an. Partikel wie Mais, Hanf oder Tigernüsse musst du vorher einweichen und kochen, roh sind sie für Fische schädlich.',
  },
  {
    id: 'aal',
    category: 'fischarten',
    question: 'Wie fange ich einen Aal?',
    all: [['aal']],
    any: ['wo', 'wann', 'fang', 'tipp', 'koeder', 'nacht', 'womit', 'angel'],
    answer: 'Aale beißen am besten in warmen, schwülen Sommernächten, gern vor Gewittern und bei steigendem, leicht trübem Wasser. Fisch mit einer Grundmontage mit Laufblei direkt am Grund, als Köder Tauwurm, Wurmbündel, Köderfisch oder Fischfetzen an Haken der Größe 1–4. Lass dem Aal nach dem Biss etwas Zeit, bevor du anschlägst. Wichtig: Der Europäische Aal ist stark gefährdet. Je nach Bundesland und Gewässer gelten besondere Mindestmaße, Entnahmegrenzen oder zeitweise Fangverbote, also prüf das unbedingt vorher.',
    page: 'RuleAssistant',
  },
  {
    id: 'wels',
    category: 'fischarten',
    question: 'Wie fange ich einen Wels?',
    all: [['wels', 'waller']],
    any: ['wo', 'wann', 'fang', 'tipp', 'koeder', 'womit', 'angel', 'montage'],
    answer: 'Welse werden bei warmem Wasser über etwa 18 °C richtig aktiv, vor allem nachts und bei Gewitterstimmung. Sie stehen in tiefen Löchern, an Totholz, unter überhängenden Bäumen und an Strömungskanten. Beliebte Köder sind Köderfische, Tauwurmbündel und Pellets an der Grund- oder U-Posen-Montage, vom Boot aus auch das Klopfen mit dem Wallerholz. Das Gerät muss kräftig sein: starke Rute, geflochtene Schnur ab 0,40 mm, sehr robustes Vorfach und große, stabile Haken. Für den Drill brauchst du Geduld und eine richtig eingestellte Bremse.',
  },
  {
    id: 'brasse',
    category: 'fischarten',
    question: 'Wie fange ich Brassen?',
    all: [['brasse', 'brassen', 'blei fangen', 'brachse']],
    any: ['wo', 'wann', 'fang', 'tipp', 'koeder', 'womit', 'feeder', 'angel'],
    answer: 'Brassen ziehen in Schwärmen über schlammigen und sandigen Grund in tieferen Bereichen. Hast du einen Schwarm mit Futter am Platz gehalten, kommen die Bisse Schlag auf Schlag. Ideal ist die Feederrute mit Futterkorb: Futter mit etwas Mais und Maden, Hakenköder Made, Wurm oder Mais an Haken der Größe 10–14 und einem 0,14–0,16 mm Vorfach von 50–100 cm. Wirf immer genau auf dieselbe Stelle (Schnurclip) und füttere zu Beginn mit mehreren schnellen Würfen vor. Beste Zeit: Dämmerung und bewölkte Tage.',
  },
  {
    id: 'rotauge',
    category: 'fischarten',
    question: 'Wie fange ich Rotaugen und Rotfedern?',
    all: [['rotauge', 'rotfeder', 'weissfisch', 'plotze', 'rotaugen']],
    answer: 'Rotaugen und Rotfedern sind perfekte Einsteigerfische und fast überall zu finden. Fisch fein: eine Pose mit 1–2 g Tragkraft, 0,10–0,12 mm Vorfach und Haken der Größe 14–18. Köder sind Made, Caster, Brotflocke oder Mais. Rotaugen fängst du knapp über Grund, Rotfedern eher im Mittelwasser oder an der Oberfläche, gern an Schilf und Seerosen. Füttere wenig, aber regelmäßig, damit der Schwarm am Platz bleibt. Mit der Stipprute bist du hier besonders schnell und präzise.',
  },
  {
    id: 'schleie',
    category: 'fischarten',
    question: 'Wie fange ich eine Schleie?',
    all: [['schleie']],
    answer: 'Schleien lieben warme, krautige Stillgewässer: Seerosenfelder, Schilfkanten und schlammigen Grund. Die beste Zeit sind frühe Sommermorgen bis etwa zehn Uhr; feine Bläschenketten an der Oberfläche verraten fressende Schleien. Fisch mit einer exakt ausgeloteten Pose, der Köder liegt knapp auf Grund — Wurm, Made, Mais oder Caster an Haken der Größe 10–14. Füttere einen kleinen Platz nah am Kraut an. Die Bisse sind oft zögerlich, warte, bis die Pose wirklich wegzieht.',
  },
  {
    id: 'doebel',
    category: 'fischarten',
    question: 'Wie fange ich einen Döbel?',
    all: [['doebel', 'aitel', 'dickkopf']],
    answer: 'Döbel sind scheue Allesfresser in Flüssen und Bächen. Sie stehen unter überhängenden Bäumen, an Brückenpfeilern und in Strömungskanten. Bleib unauffällig am Ufer, sonst sind sie weg. Gute Köder sind Brotflocke oder Brotkruste an der Oberfläche, Käse, Würmer und im Sommer Insekten. Auf Kunstköder beißen sie auch: kleine Wobbler, Spinner und Oberflächenköder, stromab treiben lassen und langsam einholen. Das Maul ist groß, der Anhieb darf kräftig kommen.',
  },

  // -------------------------------------------------------------------- Köder
  {
    id: 'koeder-allgemein',
    category: 'koeder',
    question: 'Welchen Köder soll ich nehmen?',
    all: [['koeder']],
    any: ['welch', 'best', 'gut', 'nehm', 'empfehl', 'art'],
    answer: 'Das hängt vor allem vom Zielfisch ab. Für Raubfische wie Hecht, Zander und Barsch nimmst du Kunstköder (Gummifisch, Wobbler, Spinner, Blinker) oder Köderfische. Für Friedfische wie Karpfen, Brasse und Rotauge eignen sich Naturköder: Mais, Maden, Würmer, Boilies und Pellets. Faustregeln: bei kaltem Wasser kleiner und langsamer, bei trübem Wasser grelle Farben und Köder mit Druckwelle, bei klarem Wasser natürliche Dekore. Auf welchen Fisch willst du es versuchen?',
  },
  {
    id: 'gummifisch',
    category: 'koeder',
    question: 'Wie führe ich einen Gummifisch?',
    all: [['gummifisch', 'gufi', 'shad', 'gummikoeder', 'softbait', 'twister']],
    any: ['fuehr', 'wie', 'montier', 'benutz', 'jigg', 'faulenz', 'einsetz'],
    answer: 'So führst du einen Gummifisch: 1. Montage — Jighaken passend zur Ködergröße (8 cm ≈ 2/0–3/0, 12 cm ≈ 4/0–5/0), Köder gerade aufziehen. Als Gewicht gilt etwa 1 g pro Meter Wassertiefe, mit Zuschlag bei Strömung. 2. Auswerfen und an gespannter Schnur absinken lassen, bis die Schnur erschlafft — dann ist er am Grund. 3. Jiggen: ein Rutenschlag oder 1–2 schnelle Kurbelumdrehungen, dann wieder absinken lassen. Oder Faulenzen: Rute ruhig auf 10 Uhr, nur 2–3 Kurbelumdrehungen, Pause. 4. Der Biss kommt fast immer in der Absinkphase — zuckt oder springt die Schnur, sofort anschlagen. 5. Typischer Fehler: zu schwerer Kopf, dann fällt der Köder wie ein Stein. In der 3D-Köderführung kannst du dir beides ansehen.',
    page: 'Koeder3D',
  },
  {
    id: 'jigkopf-gewicht',
    category: 'koeder',
    question: 'Wie schwer muss der Jigkopf sein?',
    all: [['jigkopf', 'jigkoepf', 'bleikopf', 'jig kopf', 'jiggewicht']],
    any: ['schwer', 'gewicht', 'gramm', 'wieviel'],
    answer: 'Faustregel: etwa 1 g pro Meter Wassertiefe, dazu ein Zuschlag bei Strömung oder Wind. Richtig gewählt ist das Gewicht, wenn der Köder nach dem Sprung 2–4 Sekunden bis zum Grund braucht. Kommt er schneller unten an, ist er zu schwer und wirkt unnatürlich; spürst du den Grund nicht mehr, ist er zu leicht. Grobe Richtwerte: Barsch 3–7 g, Zander 5–14 g, Hecht 10–30 g. Der Haken sollte zur Ködergröße passen, etwa 2/0–3/0 bei 8 cm und 4/0–5/0 bei 12 cm.',
  },
  {
    id: 'wobbler',
    category: 'koeder',
    question: 'Wie führe ich einen Wobbler?',
    all: [['wobbler', 'crankbait', 'jerkbait', 'twitchbait', 'minnow']],
    answer: 'Die Tauchtiefe hängt von der Tauchschaufel ab und steht meist auf der Verpackung. Wähle den Wobbler so, dass er knapp über Kraut oder Grund läuft. Die drei wichtigsten Führungen: gleichmäßig einkurbeln, Stop-and-Go (einkurbeln, kurz stoppen, weiter — viele Bisse kommen im Stopp) und Twitchen: mit halb lockerer Schnur kurze Schläge mit der Rutenspitze, dazwischen Pausen, dann bricht der Wobbler seitlich aus wie ein kranker Fisch. Schwimmende Modelle steigen in der Pause auf, sinkende und schwebende (Suspender) bleiben stehen, die sind im kalten Wasser besonders stark.',
    page: 'Koeder3D',
  },
  {
    id: 'spinner-blinker',
    category: 'koeder',
    question: 'Wie fische ich mit Spinner und Blinker?',
    all: [['spinner', 'blinker', 'spoon', 'loeffel']],
    answer: 'Spinner und Blinker holst du gleichmäßig so langsam ein, dass das Spinnerblatt gerade noch dreht oder der Blinker taumelt. Schneller ist selten besser. Zähl nach dem Auswurf die Absinkzeit ("21, 22, 23..."), so suchst du nacheinander verschiedene Tiefen ab und merkst dir, wo der Biss kam. Im Fluss wirfst du schräg stromauf und führst den Köder mit der Strömung. Größen: Barsch und Forelle 0–3, Hecht 4–5. Ein kleiner Wirbel vor dem Köder verhindert Schnurdrall, der bei Spinnern sonst schnell entsteht.',
  },
  {
    id: 'oberflaechenkoeder',
    category: 'koeder',
    question: 'Wie führe ich Oberflächenköder?',
    all: [['popper', 'stickbait', 'oberflaechenkoeder', 'topwater', 'walk the dog', 'oberflaeche']],
    answer: 'Oberflächenköder sind im Sommer bei ruhigem Wasser, in der Dämmerung und über Krautfeldern stark. Den Popper lässt du mit kurzen, ruckartigen Schlägen "blubbern", dazwischen Pausen von ein bis drei Sekunden. Den Stickbait führst du im Zickzack (Walk the Dog): rhythmische kleine Schläge mit der Rutenspitze bei lockerer Schnur, gleichzeitig langsam kurbeln. Beim Biss nicht sofort anschlagen — erst wenn du den Fisch wirklich spürst, sonst reißt du ihm den Köder aus dem Maul.',
    page: 'Koeder3D',
  },
  {
    id: 'wurm',
    category: 'koeder',
    question: 'Wie angle ich mit Wurm?',
    all: [['wurm', 'wuerm', 'tauwurm', 'rotwurm', 'regenwurm', 'regenwuerm', 'dendrobena', 'mistwurm']],
    any: ['lager', 'aufbewahr', 'aufzieh', 'anbiet', 'haken'],
    answer: 'Würmer sind die vielseitigsten Naturköder, fast jeder Fisch nimmt sie. Tauwürmer eignen sich für Aal, Barsch, Karpfen und Döbel, kleine Rot- und Mistwürmer für Rotauge, Schleie und Forelle. Zieh den Wurm nicht komplett auf, sondern steche ihn zwei- bis dreimal an, damit er sich noch bewegt; Hakengröße 4–8 für Tauwurm, 10–14 für kleine Würmer. Anbieten kannst du ihn an der Pose knapp über Grund oder an der Grundmontage. Lagere Würmer kühl und feucht in Erde oder Moos, niemals in der Sonne.',
  },
  {
    id: 'maden',
    category: 'koeder',
    question: 'Wie angle ich mit Maden?',
    all: [['made', 'maden', 'caster', 'pinkies']],
    answer: 'Maden sind der Allround-Köder für Friedfische wie Rotauge, Rotfeder, Brasse und Schleie, im Winter auch für Barsch und Forelle. Zieh sie am dicken Ende nur leicht an, damit sie lebendig zappeln — ein bis drei Maden an einem Haken der Größe 12–18 mit feinem Vorfach. Caster, also verpuppte Maden, sinken langsamer und fangen oft die größeren Fische. Füttere ein paar Maden regelmäßig nach, das hält den Schwarm am Platz. Lagere Maden kühl, am besten im Kühlschrank in einer luftdurchlässigen Dose.',
  },
  {
    id: 'koederfisch',
    category: 'koeder',
    question: 'Wie angle ich mit Köderfisch?',
    all: [['koederfisch', 'koefi', 'toter fisch', 'koederfische', 'fischfetzen']],
    answer: 'Tote Köderfische sind stark für Hecht, Zander, Aal und Wels. Für Zander nimmst du kleine Fische von 6–10 cm an einem Einzelhaken und schlägst früh an. Für Hecht sind 12–20 cm am System mit Drilling (z. B. Ryder) üblich; hier wartest du, bis der Hecht mit dem Fisch abzieht, aber nicht zu lange, damit er nicht schluckt. Du kannst den Köderfisch an der Pose über Grund, am Grund oder langsam geschleppt anbieten. Beachte: Lebende Köderfische sind in Deutschland verboten, und auch für Köderfische gelten die Schonzeiten und Mindestmaße ihrer Art.',
  },
  {
    id: 'boilies',
    category: 'koeder',
    question: 'Was sind Boilies?',
    all: [['boilie', 'popup', 'pop up', 'wafter']],
    answer: 'Boilies sind gekochte Teigkugeln aus Mehlen, Eiern und Lockstoffen, fester als Teig und damit selektiv: Kleinfische bekommen sie kaum klein. Größen von 15–20 mm sind Standard, größere sortieren noch stärker. Sie werden an der Haarmontage angeboten, also nicht auf den Haken gezogen, sondern auf einem kurzen Haar dahinter. Sinkende Boilies liegen am Grund, Pop-ups treiben auf (gut über Schlamm und Kraut), Wafter sinken extrem langsam und wirken besonders natürlich. Gute Boilies riechen frisch und sind nicht bröselig.',
  },
  {
    id: 'anfuettern',
    category: 'koeder',
    question: 'Wie füttere ich richtig an?',
    all: [['anfuetter', 'fuetter', 'lockfutter', 'futterplatz', 'futter', 'vorfuettern', 'partikel', 'mais kochen', 'tigernuesse kochen', 'hanf']],
    any: ['wie', 'viel', 'richtig', 'wann', 'menge'],
    answer: 'Anfüttern lockt Fische an deinen Platz und hält sie dort. Die Grundregeln: 1. Prüf die Gewässerordnung, denn Anfüttern ist nicht überall erlaubt und oft mengenmäßig begrenzt. 2. Füttere lieber wenig und regelmäßig als viel auf einmal, besonders bei kaltem Wasser. 3. Wirf das Futter immer exakt auf dieselbe Stelle, am besten mit Schnurclip oder Markierung. 4. Futter und Hakenköder sollten zusammenpassen, also Maden im Futter, wenn du mit Made fischst. 5. Partikel wie Mais, Hanf oder Tigernüsse vorher einweichen und kochen.',
  },
  {
    id: 'koeder-farbe',
    category: 'koeder',
    question: 'Welche Köderfarbe ist die richtige?',
    all: [['farbe', 'farben', 'dekor', 'farbwahl', 'koederfarbe']],
    answer: 'Grundregel: Die Farbe richtet sich nach der Sicht unter Wasser. Bei trübem Wasser und wenig Licht (Dämmerung, bewölkt) funktionieren grelle, kontrastreiche Farben wie Firetiger, Chartreuse oder Weiß, gern mit Rasseln. Bei klarem Wasser und Sonne sind natürliche Dekore wie Barsch, Rotauge oder Weißfisch-Silber und gedeckte Töne besser, dazu dünnere Vorfächer. Wichtiger als die Farbe sind aber meistens Tiefe, Tempo und Ködergröße — dreh zuerst an diesen Stellschrauben.',
  },

  // ---------------------------------------------------------------- Montagen
  {
    id: 'dropshot',
    category: 'montagen',
    question: 'Wie funktioniert die Drop-Shot-Montage?',
    all: [['drop shot', 'dropshot']],
    answer: 'So montierst und fischst du Drop Shot: 1. Binde den Haken mit einem Palomar-Knoten direkt in die Schnur (Fluorocarbon), sodass die Hakenspitze nach oben zeigt, und lass das lange Ende 30–80 cm nach unten hängen. 2. Am Ende klemmst du ein Drop-Shot-Blei von 5–15 g ein. 3. Köder: schlanke Gummiwürmer oder kleine Shads von 5–8 cm, quer durch die Nase gehakt. 4. Auswerfen, Blei am Grund liegen lassen und den Köder mit feinen Zupfern der Rutenspitze an leicht gespannter Schnur tanzen lassen, ohne ihn einzuholen. 5. Stark für träge Barsche und Zander, vom Boot auch vertikal.',
  },
  {
    id: 'texas-carolina',
    category: 'montagen',
    question: 'Was ist ein Texas- oder Carolina-Rig?',
    all: [['texas', 'carolina', 'offset', 'krautfrei']],
    answer: 'Beide Montagen machen deinen Gummiköder krautfrei. Beim Texas-Rig fädelst du ein Patronenblei (Bullet) von 5–15 g auf die Schnur, bindest einen Offset-Haken an und versteckst die Hakenspitze im Köder, so ziehst du ihn durch Kraut, Holz und Steine, wo Jigköpfe hängen bleiben. Beim Carolina-Rig sitzt das Blei vor einem Wirbel, dahinter folgt ein 50–120 cm langes Vorfach; der Köder schwebt dadurch langsam hinter dem Blei her und wirkt sehr natürlich. Führung: langsam über den Grund schleifen oder zupfen, mit Pausen.',
  },
  {
    id: 'cheburashka',
    category: 'montagen',
    question: 'Was ist eine Cheburashka-Montage?',
    all: [['cheburashka', 'tscheburaschka']],
    answer: 'Die Cheburashka ist ein austauschbares Klemmblei mit zwei Drahtösen: An eine Öse kommt die Hauptschnur, an die andere der Haken mit dem Gummiköder. Weil der Haken frei beweglich ist, spielt der Köder natürlicher als am starren Jigkopf, und du wechselst das Gewicht in Sekunden, ohne neu zu binden. Geführt wird sie wie ein Jig: gejiggt oder gefaulenzt über Grund. Ideal für Barsch und Zander, mit Offset-Haken auch in hängerträchtigen Bereichen.',
  },
  {
    id: 'posenmontage',
    category: 'montagen',
    question: 'Wie baue ich eine Posenmontage?',
    all: [['pose', 'posen', 'schwimmer', 'loten', 'ausloten', 'posenmontage']],
    answer: 'So baust du eine Posenmontage: 1. Wähle die Pose nach Gewässer: 1–3 g für ruhige Teiche, schwerer bei Wind und Strömung. 2. Fädel sie auf die Hauptschnur und blei sie mit Schrotblei so aus, dass nur noch die Antenne aus dem Wasser schaut, dann meldet sie auch vorsichtige Bisse. 3. Ans Ende kommt ein Vorfach mit Haken passend zum Köder. 4. Lote die Tiefe mit einem Lotblei aus und stelle die Pose so ein, dass der Köder knapp über oder auf dem Grund liegt. Bei tiefem Wasser nimmst du eine Laufpose mit Stopperknoten. 5. Anschlagen, wenn die Pose abtaucht oder deutlich wegzieht.',
  },
  {
    id: 'grundmontage',
    category: 'montagen',
    question: 'Wie baue ich eine Grundmontage?',
    all: [['grundmontage', 'grundangeln', 'laufblei', 'festblei', 'grundblei', 'seitenarm', 'grundrute']],
    answer: 'Die einfachste Grundmontage ist die Laufbleimontage: 1. Fädel ein Laufblei (20–60 g je nach Wurfweite und Strömung) oder einen Anti-Tangle-Boom auf die Hauptschnur. 2. Dahinter eine Gummiperle als Knotenschutz und ein Wirbel. 3. Am Wirbel ein Vorfach von 30–80 cm mit Haken. 4. Nach dem Auswurf die Schnur leicht spannen und einen Bissanzeiger einhängen oder die Rutenspitze beobachten. Der Fisch kann den Köder nehmen, ohne das Blei zu spüren. Beim Karpfenangeln nutzt man stattdessen ein Festblei, gegen das sich der Fisch selbst hakt.',
  },
  {
    id: 'haarmontage',
    category: 'montagen',
    question: 'Wie funktioniert die Haarmontage?',
    all: [['haarmontage', 'haar montage', 'selbsthak', 'rig karpfen', 'karpfenmontage', 'karpfen montage']],
    answer: 'Bei der Haarmontage sitzt der Köder, meist Boilie oder Mais, nicht auf dem Haken, sondern auf einem kurzen Schnurstück (dem Haar) hinter dem blanken Haken. So: 1. Vorfach von 15–25 cm mit einem Knotenless-Knoten an den Haken binden, dabei eine Haar-Schlaufe stehen lassen. 2. Köder mit der Ködernadel aufs Haar ziehen und mit einem Stopper sichern, Abstand zum Hakenbogen etwa 1 cm. 3. Mit einem 60–100 g Festblei kombinieren. Saugt der Karpfen den Köder ein und schwimmt weg, zieht ihn das Blei gegen die Hakenspitze — er hakt sich selbst.',
  },
  {
    id: 'feeder',
    category: 'montagen',
    question: 'Wie funktioniert Feederangeln?',
    all: [['feeder', 'method feeder', 'method$', 'futterkorb', 'futterkoerb', 'feederrute']],
    answer: 'Beim Feederangeln sitzt ein Futterkorb an der Montage und legt das Futter direkt neben deinen Hakenköder. Die feine Spitze der Feederrute zeigt den Biss an. So geht es: Schnurclip auf die gewünschte Wurfweite, zu Beginn 6–10 Würfe mit gefülltem Korb, um einen Futterteppich zu legen, dann alle paar Minuten neu werfen. Vorfach 50–100 cm, 0,14–0,18 mm. Beim Method Feeder drückst du das Futter um einen flachen Korb und bettest einen Pellet- oder Mini-Boilie-Köder am Haar direkt ins Futter ein, bei straffer Schnur haken sich die Fische meist selbst.',
  },
  {
    id: 'sbirolino',
    category: 'montagen',
    question: 'Wie funktioniert die Sbirolino-Montage?',
    all: [['sbirolino', 'bombarde', 'tremarella', 'wurfgewicht forelle']],
    answer: 'Der Sbirolino ist ein Wurfgewicht, mit dem du leichte Köder wie Forellenteig, Bienenmaden oder Fliegen weit werfen kannst. Montage: Sbirolino auf die Hauptschnur, Perle, Wirbel, dahinter ein langes Vorfach von 1,5–3 m (0,16–0,18 mm) mit kleinem Haken. Nach dem Wurf je nach Modell kurz absinken lassen und dann sehr langsam einholen, gern mit leichten Zupfern oder Zittern der Rutenspitze. Die Tremarella ist die Variante mit ständigem Zittern der Rute, ideal an Forellenseen.',
  },
  {
    id: 'vorfach',
    category: 'montagen',
    question: 'Welches Vorfach brauche ich?',
    all: [['vorfach', 'stahlvorfach', 'titanvorfach', 'fluorocarbon', 'fluoro']],
    answer: 'Beim Spinnfischen auf Barsch und Zander hängst du vor die geflochtene Hauptschnur 0,5–1 m Fluorocarbon (Barsch 0,18–0,25 mm, Zander 0,25–0,35 mm), das ist abriebfest und unter Wasser kaum sichtbar. Wo Hechte vorkommen können, gilt Pflicht: ein Stahl- oder Titanvorfach oder mindestens 0,80 mm dickes Fluorocarbon, sonst droht Abbiss und der Fisch schwimmt mit Köder im Maul davon. Beim Friedfischangeln nimmst du Monofil, etwas dünner als die Hauptschnur, damit bei einem Hänger nur das Vorfach reißt.',
  },

  // ------------------------------------------------------------------- Knoten
  {
    id: 'knoten-allgemein',
    category: 'knoten',
    question: 'Welche Knoten brauche ich?',
    all: [['knoten']],
    any: ['welch', 'wichtig', 'brauch', 'best', 'binden'],
    answer: 'Mit vier Knoten kommst du fast überall durch: Der verbesserte Clinch-Knoten ist der Standard für Haken und Wirbel an Monofil und Fluorocarbon. Der Palomar ist der stärkste einfache Knoten, ideal für Geflecht und Drop Shot. Albright oder FG verbinden Geflecht mit Fluorocarbon-Vorfach. Der Rapala-Schlaufenknoten gibt Wobblern freies Spiel. Für alle gilt: vor dem Zuziehen anfeuchten, langsam zuziehen und danach mit Zug testen. Sag mir, welchen ich dir Schritt für Schritt erklären soll — im Knoten-Assistenten siehst du sie auch als Anleitung.',
    page: 'ARKnotenAssistent',
  },
  {
    id: 'clinch',
    category: 'knoten',
    question: 'Wie binde ich einen Clinch-Knoten?',
    all: [['clinch', 'klinch']],
    any: ['knoten', 'bind', 'wie'],
    answer: 'So bindest du den verbesserten Clinch-Knoten: 1. Fädel etwa 15 cm Schnur durch das Hakenöhr oder den Wirbel. 2. Wickle das freie Ende 5–7 Mal um die Hauptschnur (bei dicker Schnur eher 5, bei dünner 7). 3. Führ das Ende durch die kleine Schlaufe direkt am Öhr. 4. Dann durch die große Schlaufe, die dabei entstanden ist, zurückstecken. 5. Anfeuchten, langsam an der Hauptschnur zuziehen, bis die Windungen sauber aufliegen, und das Ende kürzen. Für geflochtene Schnur ist der Palomar die bessere Wahl.',
    page: 'ARKnotenAssistent',
  },
  {
    id: 'palomar',
    category: 'knoten',
    question: 'Wie binde ich einen Palomar-Knoten?',
    all: [['palomar']],
    any: ['knoten', 'bind', 'wie'],
    answer: 'So bindest du den Palomar-Knoten: 1. Leg etwa 15 cm Schnur doppelt und schieb die Schlaufe durch das Hakenöhr. 2. Mach mit der doppelten Schnur einen einfachen Überhandknoten, der Haken hängt dabei lose in der Schlaufe. 3. Stülp die Schlaufe über den ganzen Haken beziehungsweise Köder. 4. Anfeuchten und an Hauptschnur und Ende gleichzeitig zuziehen, dann das Ende kürzen. Für Drop Shot führst du die Schnur von oben durchs Öhr und lässt das lange Ende nach unten hängen — so steht der Haken mit der Spitze nach oben ab.',
    page: 'ARKnotenAssistent',
  },
  {
    id: 'schnurverbindung',
    category: 'knoten',
    question: 'Wie verbinde ich Geflecht und Fluorocarbon?',
    all: [['albright', 'fg knoten', 'fg', 'verbindungsknoten', 'schnur verbinden', 'schnuere verbinden', 'geflecht mit fluoro', 'geflecht und fluoro']],
    any: ['knoten', 'bind', 'verbind', 'geflecht', 'fluoro'],
    answer: 'Am schnellsten gelingt der Albright-Knoten: 1. Leg das Fluorocarbon-Ende zu einer etwa 5 cm langen Schlaufe. 2. Schieb 15 cm Geflecht von hinten durch die Schlaufe. 3. Wickle das Geflecht 10–12 Mal eng um beide Schlaufenschenkel, und zwar in Richtung Schlaufenende. 4. Führ das Geflecht auf derselben Seite, auf der es hineinkam, wieder durch die Schlaufe hinaus. 5. Anfeuchten, erst langsam die Windungen zusammenschieben, dann alle Enden fest zuziehen und kürzen. Der FG-Knoten ist noch schlanker und hält am besten, braucht aber etwas Übung.',
    page: 'ARKnotenAssistent',
  },
  {
    id: 'schlaufenknoten',
    category: 'knoten',
    question: 'Wie binde ich einen Schlaufenknoten für Wobbler?',
    all: [['rapala knoten', 'schlaufenknoten', 'loop knoten', 'loopknoten', 'rapala schlaufe']],
    any: ['knoten', 'bind', 'wobbler', 'jig', 'koeder'],
    answer: 'Der Rapala-Schlaufenknoten gibt Wobblern und Jigs ohne Snap freies Spiel: 1. Mach etwa 10 cm vor dem Schnurende einen lockeren Überhandknoten. 2. Führ das Ende durch die Köderöse und zurück durch den Überhandknoten, auf derselben Seite, auf der es herauskam. 3. Wickle das Ende 3–4 Mal um die Hauptschnur. 4. Steck es zurück durch den Überhandknoten und dann durch die neu entstandene Schlaufe. 5. Anfeuchten und zuziehen, dabei die Schlaufe klein halten. Das Ende kürzen.',
    page: 'ARKnotenAssistent',
  },

  // -------------------------------------------------------------- Ausrüstung
  {
    id: 'ausruestung-grundausstattung',
    category: 'ausruestung',
    question: 'Was brauche ich als Grundausrüstung?',
    all: [['grundausruestung', 'grundausstattung', 'ausruestung', 'zubehoer', 'packliste', 'was mitnehmen', 'einpacken', 'erstausstattung']],
    answer: 'Für den Start brauchst du: eine Rute mit passender Rolle und Schnur (für den Anfang eine 2,70–3,60 m Allround- oder Feederrute, 2500er-Rolle, 0,20–0,22 mm Mono), ein Sortiment Haken (Größe 6–14), Posen, Bleie, Wirbel und Vorfächer. Unverzichtbar für den waidgerechten Umgang mit dem Fisch sind ein Kescher, ein Hakenlöser oder eine Zange, ein Maßband und bei Entnahme ein Fischtöter und ein Messer. Dazu Fischereischein, Gewässerkarte, wetterfeste Kleidung und eine Sitzgelegenheit. Deine Sachen kannst du in der App unter Ausrüstung verwalten.',
    page: 'Gear',
  },
  {
    id: 'rute',
    category: 'ausruestung',
    question: 'Welche Angelrute brauche ich?',
    all: [['rute', 'ruten', 'angelrute', 'spinnrute', 'wurfgewicht']],
    any: ['kauf', 'waehl', 'empfehl', 'lang', 'barsch', 'zander', 'hecht', 'karpf', 'forelle', 'friedfisch', 'feeder', 'spinn', 'anfaenger'],
    answer: 'Die Rute richtet sich nach Methode und Zielfisch. Zum Spinnfischen ist eine 2,40–2,70 m Rute ein guter Allrounder: für Barsch mit 5–20 g Wurfgewicht, für Zander 10–40 g, für Hecht 20–80 g. Zum Posen- und Grundangeln auf Friedfische passt eine 3–3,60 m Feeder- oder Allroundrute, für Karpfen eine 3,60 m Karpfenrute mit 2,75–3,5 lbs. Achte darauf, dass das Wurfgewicht zu deinen Ködern passt — ein zu leichter Köder lädt die Rute nicht auf, ein zu schwerer überlastet sie.',
    page: 'Gear',
  },
  {
    id: 'rolle',
    category: 'ausruestung',
    question: 'Welche Rolle passt zu meiner Rute?',
    all: [['rolle', 'stationaerrolle', 'baitcaster', 'multirolle', 'freilaufrolle']],
    any: ['groess', 'kauf', 'rute', 'barsch', 'zander', 'hecht', 'karpf', 'forelle', 'wels', 'feeder', 'spinn'],
    answer: 'Als Faustregel: Die Rolle sollte zur Rute passen und die Kombination in der Hand gut ausbalanciert sein. Größe 1000–2500 für leichtes Spinnfischen auf Barsch und Forelle, 2500–4000 für Zander, Hecht und Feederangeln, 5000 und größer bzw. Freilauf- oder Big-Pit-Rollen fürs Karpfen- und Welsangeln. Wichtig sind eine fein einstellbare Bremse, eine saubere Schnurverlegung und eine Ersatzspule. Baitcaster sind für schwere Köder beim Hechtangeln stark, brauchen aber Übung beim Werfen.',
    page: 'Gear',
  },
  {
    id: 'schnur',
    category: 'ausruestung',
    question: 'Welche Schnur soll ich nehmen?',
    all: [['schnur', 'geflecht', 'geflochten', 'monofil', 'monoschnur', 'hauptschnur']],
    any: ['dick', 'durchmesser', 'staerk', 'unterschied', 'nehm', 'mono$', 'geflecht', 'barsch', 'zander', 'hecht', 'karpf', 'friedfisch'],
    answer: 'Geflochtene Schnur dehnt sich kaum, überträgt jeden Zupfer und ist bei gleicher Tragkraft viel dünner — ideal zum Spinnfischen: Barsch 0,06–0,10 mm, Zander 0,10–0,13 mm, Hecht 0,13–0,17 mm, immer mit Fluorocarbon- oder Stahlvorfach. Monofile Schnur ist dehnbar und verzeiht Fehler im Drill, deshalb erste Wahl beim Posen-, Grund- und Karpfenangeln: Friedfisch 0,18–0,25 mm, Karpfen 0,30–0,35 mm. Füll die Spule bis etwa 2 mm unter den Rand und tausche Mono spätestens jede Saison.',
  },
  {
    id: 'bremse',
    category: 'ausruestung',
    question: 'Wie stelle ich die Bremse ein?',
    all: [['bremse', 'bremseinstellung', 'rollenbremse']],
    any: ['einstell', 'stelle$', 'fest', 'locker'],
    answer: 'Stell die Bremse vor dem ersten Wurf auf etwa ein Drittel der Schnurtragkraft ein. Praktisch: Schnur durch die Ringe ziehen und vor der Rolle per Hand abziehen — unter kräftigem Zug soll die Rolle gleichmäßig surrend Schnur freigeben, ohne zu ruckeln. Ist sie zu fest, reißt bei einer Flucht die Schnur oder der Haken schlitzt aus; ist sie zu locker, bekommst du keinen Druck auf den Fisch. Im Drill nie gegen die ablaufende Bremse kurbeln, das verdreht nur die Schnur.',
  },
  {
    id: 'schnurdrall',
    category: 'ausruestung',
    question: 'Warum verdrallt meine Schnur?',
    all: [['peruecke', 'verdrallt', 'drall', 'schnursalat', 'verheddert', 'kringelt', 'luftknoten']],
    any: ['schnur', 'rolle', 'spinner', 'geflecht'],
    answer: 'Schnurdrall und Perücken haben meist diese Ursachen: Kurbeln, während die Bremse Schnur abgibt; drehende Köder wie Spinner ohne Wirbel; zu voll gespulte Rolle; und lockere Schnur beim Einkurbeln, besonders bei Geflecht. Abhilfe: Spule nur bis 2 mm unter den Rand füllen, nach dem Wurf den Bügel per Hand schließen und die Schnur kurz straffen, bei Spinnern einen kleinen Wirbel vorschalten. Hat sich Mono schon verdreht, lass sie ohne Köder hinter einem fahrenden Boot oder in der Strömung ablaufen und spul sie unter Spannung neu auf.',
  },
  {
    id: 'echolot',
    category: 'ausruestung',
    question: 'Lohnt sich ein Echolot?',
    all: [['echolot', 'sonar', 'fishfinder', 'wurfecholot', 'castable']],
    answer: 'Ein Echolot zeigt dir Tiefe, Bodenhärte, Kanten, Kraut und Fischsicheln — du findest Standplätze viel schneller, statt blind abzufischen. Vom Ufer aus gibt es werfbare Echolote, die per Bluetooth aufs Handy funken. Wichtig beim Lesen: Nicht jede Sichel ist ein Zielfisch; entscheidender sind Strukturen wie Kanten, Plateaus und Löcher. Werfbare Echolote und andere Bluetooth-Geräte verbindest du in der App unter Geräte.',
    page: 'Devices',
  },
  {
    id: 'ausruestung-pflege',
    category: 'ausruestung',
    question: 'Wie pflege ich meine Angelausrüstung?',
    all: [['pflege', 'pflegen', 'reinig', 'wartung', 'warten', 'oelen', 'fetten'], ['rolle', 'rute', 'ausruestung', 'schnur', 'geraet', 'tackle', 'haken', 'wathose']],
    answer: 'Ein paar Handgriffe verlängern die Lebensdauer deutlich: 1. Nach jedem Einsatz Rute und Rolle mit Süßwasser abspülen, nach Salzwasser unbedingt, und trocknen lassen. 2. Rutenringe auf Risse prüfen, zum Beispiel mit einem Wattestäbchen, denn raue Ringe zerstören die Schnur. 3. Rolle regelmäßig an Kurbel, Bügel und Achse leicht ölen, die Bremse beim Lagern lockern. 4. Schnur auf Aufrauungen prüfen und die ersten Meter regelmäßig abschneiden. 5. Haken nachschärfen oder tauschen und die Köderbox trocknen, damit nichts rostet. Im Wartungsprotokoll behältst du den Überblick.',
    page: 'GearMaintenance',
  },

  // --------------------------------------------------------- Technik & Drill
  {
    id: 'auswerfen',
    category: 'technik',
    question: 'Wie werfe ich richtig aus?',
    all: [['auswerfen', 'werf', 'wirf', 'wurfweite', 'wurftechnik', 'wurf$']],
    any: ['weit', 'lern', 'rolle'],
    answer: 'So wirfst du mit einer Stationärrolle: 1. Köder etwa 30–50 cm unter die Rutenspitze hängen lassen. 2. Schnur mit dem Zeigefinger an der Rute festhalten und den Bügel öffnen. 3. Rute hinter den Kopf führen, kurz warten, bis sie sich spannt, und dann zügig nach vorn beschleunigen. 4. Schnur loslassen, wenn die Rute etwa auf 11 Uhr steht; zu früh geht der Wurf steil nach oben, zu spät klatscht er vor dir ins Wasser. 5. Vor dem Aufprall die ablaufende Schnur mit dem Finger abbremsen und den Bügel von Hand schließen, so vermeidest du Perücken. Mehr Weite bringen eine volle Spule und ein ruhiger, durchgezogener Schwung statt roher Kraft.',
  },
  {
    id: 'anschlag',
    category: 'technik',
    question: 'Wann und wie schlage ich an?',
    all: [['anschlag', 'anschlagen', 'anhieb', 'schlage ich an']],
    answer: 'Das hängt von Methode und Fisch ab. Beim Spinnfischen schlägst du sofort und kräftig an, wenn du einen Ruck spürst oder die Schnur zuckt — bei Zander besonders energisch, weil das Maul hart ist. Beim Posenangeln wartest du, bis die Pose abtaucht oder zügig wegzieht. Mit Köderfisch auf Hecht lässt du ihn kurz abziehen, aber nicht so lange, dass er schluckt. Bei Selbsthakmontagen fürs Karpfenangeln reicht es, die Rute aufzunehmen und Kontakt herzustellen. Mit Geflecht genügt ein kurzer, straffer Anhieb, mit dehnbarer Mono darf er weiter durchgezogen werden.',
  },
  {
    id: 'biss-erkennen',
    category: 'technik',
    question: 'Wie erkenne ich einen Biss?',
    all: [['biss', 'bisserkenn', 'bissanzeig', 'zupfer', 'zupfen']],
    any: ['erkenn', 'merk', 'sehe', 'wie', 'spuer', 'anzeig'],
    answer: 'Beim Spinnfischen spürst du einen Ruck oder ein "Tock" in der Rute. Bei Gummifischen siehst du den Biss oft nur daran, dass die Schnur in der Absinkphase zuckt, springt oder früher als erwartet schlaff wird — deshalb die Schnur immer im Auge behalten. Beim Posenangeln taucht die Pose ab, zieht zur Seite oder legt sich hin (Heben-Biss). Beim Grundangeln zupft oder biegt sich die Rutenspitze, oder der Bissanzeiger piept und die Schnur läuft ab. Wichtig ist eine leicht gespannte Schnur, sonst kommt der Biss gar nicht bei dir an.',
  },
  {
    id: 'drill',
    category: 'technik',
    question: 'Wie drille ich einen Fisch richtig?',
    all: [['drill$', 'drille$', 'drillen', 'drillt$', 'fisch landen', 'landung', 'keschern', 'kescher$']],
    answer: 'So drillst und landest du sicher: 1. Rute im Winkel von 45–90 Grad halten und nie direkt auf den Fisch zeigen, dann federt sie die Fluchten ab. 2. Pumpen: Rute langsam anheben, beim Absenken Schnur einkurbeln. 3. Fluchten laufen lassen, die Bremse arbeitet für dich, und nicht gegen die ablaufende Bremse kurbeln. 4. Hindernisse vermeiden, indem du den Fisch mit seitlichem Rutendruck weglenkst. 5. Erst keschern, wenn der Fisch müde an der Oberfläche liegt: Kescher ins Wasser halten und den Fisch kopfvoran hineinführen, nicht hinterher stechen. Gummierte Netze schonen die Schleimhaut.',
  },
  {
    id: 'fehlbisse',
    category: 'technik',
    question: 'Warum verliere ich Fische oder habe Fehlbisse?',
    all: [['fehlbiss', 'aussteiger', 'ausgeschlitzt', 'ausschlitz', 'verliere', 'verloren', 'haengt nicht', 'nicht haengen', 'abgefallen']],
    any: ['drill', 'haken', 'biss'],
    answer: 'Häufige Gründe und was hilft: Stumpfe Haken — prüfe die Spitze am Daumennagel, sie muss haften, sonst schärfen oder tauschen. Zu fest eingestellte Bremse oder zu harter Drill mit Geflecht reißen den Haken aus, also Bremse auf ein Drittel der Tragkraft und gleichmäßig Druck halten. Zu großer Köder für den Haken: Bei Gummifischen im hinteren Drittel einen Angsthaken (Stinger) setzen. Zu spät oder zu zaghaft angeschlagen, besonders beim harten Zandermaul. Und beim Friedfischangeln: kleinerer Haken und feineres Vorfach, wenn die Fische nur zupfen.',
  },
  {
    id: 'haenger',
    category: 'technik',
    question: 'Was mache ich bei einem Hänger?',
    all: [['haenger', 'festgehakt', 'haengen geblieben', 'haengt fest', 'abriss', 'abrisse']],
    answer: 'Nicht sofort mit Gewalt ziehen. Erst die Schnur locker lassen: Oft löst sich der Köder durch sein Eigengewicht. Dann die Position wechseln und aus der Gegenrichtung ziehen. Hilft das nicht, die Schnur leicht gespannt lassen und wie eine Bogensehne anzupfen. Bleibt er fest, die Schnur um ein Stück Holz oder den Ärmel wickeln (nie um die Hand) und langsam gerade ziehen, bis etwas nachgibt. Weniger Hänger bekommst du mit leichteren Jigköpfen, Texas-Rig mit Offset-Haken und indem du den Köder im Kraut nicht absinken lässt. Abgerissene Schnur bitte immer mitnehmen.',
  },
  {
    id: 'spinnfischen',
    category: 'technik',
    question: 'Wie funktioniert Spinnfischen?',
    all: [['spinnfisch', 'spinnangeln', 'kunstkoederangeln', 'mit kunstkoeder']],
    answer: 'Beim Spinnfischen bist du aktiv unterwegs: Du wirfst einen Kunstköder aus und führst ihn so, dass er einen Beutefisch imitiert. Zielfische sind Barsch, Zander, Hecht, Forelle und Döbel. Du brauchst eine 2,40–2,70 m Spinnrute, eine 2500–4000er Rolle mit geflochtener Schnur und ein Fluorocarbon- oder Stahlvorfach. Such den Platz systematisch ab: fächerförmig werfen, verschiedene Tiefen probieren und nach 10–15 Würfen ohne Kontakt ein paar Meter weitergehen. Die Pausen in der Köderführung bringen oft die Bisse.',
  },
  {
    id: 'vertikalangeln',
    category: 'technik',
    question: 'Wie funktioniert Vertikalangeln?',
    all: [['vertikal', 'vertikalangeln', 'faulenzen vom boot']],
    answer: 'Beim Vertikalangeln fischst du vom Boot direkt unter dir: Den Gummifisch am Jigkopf lässt du senkrecht zum Grund ab, dann hebst du ihn mit kurzen, ruhigen Bewegungen 10–30 cm an und lässt ihn wieder absinken. Er bleibt dabei im Sichtfeld der Fische, auch wenn sie träge sind. Stark im Herbst und Winter auf Zander und Barsch in tiefen Löchern und an Kanten. Wichtig: Das Boot muss langsam driften oder mit dem E-Motor gehalten werden, damit die Schnur senkrecht bleibt; der Biss kommt meist als feiner Tock beim Anheben.',
  },
  {
    id: 'stippen',
    category: 'technik',
    question: 'Was ist Stippen?',
    all: [['stipp', 'kopfrute', 'stippangeln', 'stipprute']],
    answer: 'Stippen ist Posenangeln ohne Rolle: Die Schnur ist direkt an der Spitze einer langen Stipprute (4–10 m) befestigt. Dadurch präsentierst du den Köder extrem präzise und fein, perfekt für Rotauge, Rotfeder, Brasse und kleine Karpfen. Montage: feine Pose (0,5–2 g), 0,10–0,12 mm Vorfach, Haken 14–20, Köder Made, Caster oder Brot. Die Schnur ist etwa so lang wie die Rute, bei Wind etwas kürzer. Füttere kleine Kugeln präzise auf den Platz und schlag sofort an, wenn die Pose zuckt.',
  },
  {
    id: 'fliegenfischen',
    category: 'technik',
    question: 'Wie fange ich mit dem Fliegenfischen an?',
    all: [['fliegenfisch', 'fliegenrute', 'fliegenschnur', 'nymphe', 'trockenfliege', 'streamer']],
    answer: 'Beim Fliegenfischen wirfst du nicht den Köder, sondern die schwere Fliegenschnur, die die fast gewichtslose Fliege mitnimmt. Für den Einstieg auf Forelle und Äsche passt eine 9-Fuß-Rute der Klasse 5 mit schwimmender Schnur. Du fischst mit Trockenfliegen an der Oberfläche, Nymphen knapp über dem Grund oder Streamern, die Kleinfische imitieren. Die Wurftechnik lernst du am besten in einem Kurs oder auf einer Wiese, bevor es ans Wasser geht. Tipp: Beobachte, welche Insekten gerade schlüpfen, und wähle eine ähnliche Fliege.',
  },

  // -------------------------------------------------- Wetter & Bedingungen
  {
    id: 'beste-tageszeit',
    category: 'bedingungen',
    question: 'Zu welcher Tageszeit beißen Fische am besten?',
    all: [['tageszeit', 'uhrzeit', 'beisszeit', 'angelzeit', 'beste zeit', 'wann beissen', 'wann beisst', 'morgens oder abends', 'daemmerung', 'fruehmorgens']],
    answer: 'Die Dämmerungsphasen am Morgen und am Abend sind fast immer die besten Zeiten: Der Lichtwechsel löst bei vielen Arten Fressphasen aus, und Raubfische jagen im Zwielicht besonders erfolgreich. Im Sommer lohnen sich frühe Morgenstunden und die Nacht (Zander, Aal, Wels, Karpfen), während tagsüber bei Hitze wenig geht. Im Winter ist dagegen oft die Mittagszeit am besten, wenn sich das Wasser etwas erwärmt. Barsche jagen gern tagsüber. Wetterumschwünge und bewölkte Tage verlängern die Beißzeiten.',
  },
  {
    id: 'wetter-allgemein',
    category: 'bedingungen',
    question: 'Bei welchem Wetter beißen Fische am besten?',
    all: [['wetter', 'bewoelk', 'sonnig', 'sonnenschein', 'bedeckt', 'wetterumschwung', 'wetterlage']],
    any: ['welch', 'best', 'gut', 'beiss', 'angel', 'fisch', 'einfluss'],
    answer: 'Stabiles, leicht bewölktes Wetter mit etwas Wind ist für viele Arten ideal: Die gekräuselte Oberfläche dämpft das Licht, und die Fische werden mutiger. Kurz vor einer Wetterfront mit fallendem Luftdruck sind Raubfische oft besonders aktiv. Direkt nach einem Kälteeinbruch oder bei strahlendem Sonnenschein mit Hochdruck beißen sie dagegen zäh, dann helfen kleinere Köder, feinere Montagen und tiefere, schattige Stellen. Das aktuelle Wetter und die Vorhersage mit Angelbezug findest du auf der Wetter-Seite.',
    page: 'Weather',
  },
  {
    id: 'luftdruck',
    category: 'bedingungen',
    question: 'Welchen Einfluss hat der Luftdruck?',
    all: [['luftdruck', 'hochdruck', 'tiefdruck', 'barometer', 'hpa', 'hektopascal']],
    answer: 'Der Luftdruck ist einer der besten Hinweise aufs Beißverhalten. Fallender Druck vor einer Front macht Raubfische oft aktiv, das sind die klassischen Sternstunden. Stabiler Druck über mehrere Tage bringt verlässliche Bedingungen, weil sich die Fische eingestellt haben. Steigender Druck und stabiles Hochdruckwetter nach einer Front, oft mit Ostwind, lässt die Bisse zäh werden. Dann fischst du mit Finesse-Methoden wie Drop Shot, kleineren Ködern und langsamer Führung. Nicht der absolute Wert zählt, sondern die Veränderung über die letzten Tage.',
  },
  {
    id: 'wind',
    category: 'bedingungen',
    question: 'Ist Wind gut zum Angeln?',
    all: [['wind', 'windig', 'windseite', 'ostwind', 'westwind', 'sturm']],
    answer: 'Mäßiger Wind ist meist ein Vorteil: Er kräuselt die Oberfläche, reichert das Wasser mit Sauerstoff an und treibt Nahrung ans windzugewandte Ufer — dort sammeln sich Kleinfische und damit auch Raubfische und Karpfen. Fisch also gern mit dem Wind im Gesicht, auch wenn das Werfen schwerer fällt; nimm dann etwas schwerere Köder. Ostwind geht oft mit stabilem Hochdruck und zäherem Beißen einher. Bei Sturm und Böen gilt: Sicherheit zuerst, besonders auf dem Boot und unter Bäumen.',
  },
  {
    id: 'regen',
    category: 'bedingungen',
    question: 'Beißen Fische bei Regen?',
    all: [['regen$', 'regnet', 'regentag', 'regenwetter', 'nieselregen', 'regenschauer', 'regnerisch']],
    answer: 'Ja, oft sogar gut. Leichter bis mäßiger Regen dämpft das Licht, bringt Sauerstoff ins Wasser und spült Nahrung von Land hinein; viele Fische werden dann mutiger, besonders Barsch, Forelle, Döbel und Aal. Die Phase vor dem Regen mit fallendem Luftdruck ist häufig die beste. Langer Starkregen trübt und kühlt das Wasser stark ab, in Flüssen steigt es; dann such ruhigere Bereiche und greif zu auffälligen Ködern oder Geruchsködern. Bei Gewitter sofort einpacken.',
  },
  {
    id: 'gewitter',
    category: 'sicherheit',
    question: 'Was tue ich bei Gewitter am Wasser?',
    all: [['gewitter', 'blitz', 'donner', 'unwetter']],
    answer: 'Bei Gewitter gilt: sofort aufhören! Carbonruten leiten Strom hervorragend, und am offenen Wasser bist du oft der höchste Punkt. Hörst du Donner, ist das Gewitter nah genug für Blitzeinschläge. Leg die Ruten flach ab, verlass das Ufer und such Schutz im Auto oder in einem festen Gebäude, nicht unter einzeln stehenden Bäumen und nicht im Zelt oder unter dem Schirm. Vom Boot aus sofort ans Ufer. Weiterangeln erst etwa 30 Minuten nach dem letzten Donner. Die App zeigt bei Unwetterwarnungen automatisch einen Sicherheitshinweis.',
  },
  {
    id: 'wassertemperatur',
    category: 'bedingungen',
    question: 'Wie wichtig ist die Wassertemperatur?',
    all: [['wassertemperatur', 'temperatur', 'kaltes wasser', 'warmes wasser', 'wasser kalt', 'wasser warm']],
    any: ['wichtig', 'einfluss', 'welch', 'grad', 'best', 'beiss'],
    answer: 'Sehr wichtig, denn Fische sind wechselwarm: Die Wassertemperatur bestimmt ihren Stoffwechsel und damit, wie viel sie fressen. Unter etwa 8 °C werden die meisten Arten träge, dann fischst du langsam, tief und mit kleinen Ködern. Zwischen 12 und 20 °C sind die meisten Friedfische und Raubfische richtig aktiv; Karpfen und Schleie mögen es gern über 15 °C. Über 25 °C wird der Sauerstoff knapp, und die Fische ziehen sich in tiefere, kühlere oder strömungsreiche Bereiche zurück. Forellen und Saiblinge bevorzugen generell kühles Wasser.',
  },
  {
    id: 'mond',
    category: 'bedingungen',
    question: 'Beeinflusst der Mond das Beißverhalten?',
    all: [['mond', 'vollmond', 'neumond', 'mondphase', 'solunar']],
    answer: 'Möglicherweise, aber der Effekt ist kleiner als der von Wetter, Luftdruck und Wassertemperatur. Die Solunar-Theorie sagt Fressphasen voraus, wenn der Mond hoch am Himmel oder genau unter dem Horizont steht, dazu kommen Auf- und Untergang. Viele Angler berichten von guten Nächten rund um Voll- und Neumond, wissenschaftlich belegt ist das aber nur schwach. Nutze Mondphasen deshalb als Zusatzinfo: Passen Wetter und Mondphase zusammen, lohnt sich der Ansitz besonders.',
  },
  {
    id: 'wasser-truebung',
    category: 'bedingungen',
    question: 'Wie angle ich bei trübem Wasser oder Hochwasser?',
    all: [['hochwasser', 'truebes wasser', 'trueb', 'truebung', 'klares wasser', 'sichttiefe', 'glasklar']],
    answer: 'Bei trübem Wasser jagen Fische mehr mit Seitenlinie und Geruch als mit den Augen. Nimm grelle, kontrastreiche Köder mit Druckwelle oder Rasseln (Firetiger, Chartreuse, Spinnerblatt) und Naturköder mit viel Geruch wie Tauwurm oder Fischfetzen. Zander, Aal und Döbel mögen solche Bedingungen. Bei Hochwasser im Fluss ziehen sich die Fische in ruhige Bereiche zurück: Buhnenfelder, Hafeneinfahrten, überflutete Ufer und Einläufe. Bei glasklarem Wasser dagegen natürlich, fein und auf Abstand fischen. Bei Hochwasser vorsichtig am Ufer, der Boden ist oft unterspült.',
  },

  // ------------------------------------------------------------ Jahreszeiten
  {
    id: 'fruehling',
    category: 'jahreszeit',
    question: 'Wie angle ich im Frühling?',
    all: [['fruehling', 'fruehjahr', 'maerz', 'april']],
    answer: 'Im Frühjahr erwärmen sich flache Buchten, Gräben und windgeschützte Ufer zuerst, dorthin ziehen Kleinfische und damit bald auch die Räuber. Viele Arten laichen jetzt, also beachte unbedingt die Schonzeiten von Hecht, Zander und Barsch in deinem Bundesland. Friedfische wie Rotauge, Brasse und Schleie werden mit steigenden Temperaturen aktiver, Karpfen ab etwa 12 °C. Füttere sparsam, denn die Fische fressen noch nicht viel, und fisch in der wärmsten Tageszeit am Nachmittag.',
    page: 'RuleAssistant',
  },
  {
    id: 'sommer',
    category: 'jahreszeit',
    question: 'Wie angle ich im Sommer?',
    all: [['sommer', 'hitze', 'hochsommer', 'juli', 'august', 'heiss$']],
    answer: 'Im Sommer verlagert sich das Beißen in die Randzeiten: früh morgens, abends und nachts. Tagsüber stehen die Fische bei Hitze tiefer, im Schatten von Bäumen und Seerosen oder dort, wo Wind und Strömung Sauerstoff bringen. Zander ziehen nachts ins Flache, Aal und Wels sind in warmen Nächten besonders aktiv, und Karpfen kannst du an der Oberfläche mit Brot oder Schwimmbrot fangen. Oberflächenköder sind in der Dämmerung stark. Achte bei Hitze darauf, entnommene Fische sofort zu kühlen.',
  },
  {
    id: 'herbst',
    category: 'jahreszeit',
    question: 'Wie angle ich im Herbst?',
    all: [['herbst', 'oktober', 'november', 'september']],
    answer: 'Der Herbst ist die beste Raubfischzeit: Hecht, Zander und Barsch fressen sich Winterspeck an und nehmen gern größere Köder. Die Fische folgen den Kleinfischschwärmen, die sich mit fallender Temperatur an Kanten und in tieferen Bereichen sammeln. Oft beißt es jetzt den ganzen Tag, besonders bei bewölktem, windigem Wetter. Auch Karpfen fressen noch einmal kräftig, bevor das Wasser kalt wird. Denk daran, dass Bachforellen jetzt meist Schonzeit haben.',
  },
  {
    id: 'winter',
    category: 'jahreszeit',
    question: 'Kann man im Winter angeln?',
    all: [['winter', 'januar', 'februar', 'dezember', 'kaelte', 'eisig', 'frost']],
    answer: 'Ja, mit angepasster Taktik. Die Fische sind bei kaltem Wasser träge und stehen tief und konzentriert, oft in Löchern, Häfen und an tiefen Kanten. Führ die Köder sehr langsam: Faulenzen, Vertikalangeln oder Drop Shot auf Zander und Barsch, kleine Köder und feine Vorfächer. Die beste Zeit ist meist die Mittagszeit, wenn das Wasser minimal wärmer ist. Friedfische beißen vorsichtig, also nur wenig Futter und kleine Haken. Und bitte nie auf Eis gehen, dessen Tragfähigkeit du nicht sicher kennst.',
  },

  // ------------------------------------------------------- Gewässer & Spots
  {
    id: 'spot-finden',
    category: 'gewaesser',
    question: 'Wie finde ich einen guten Angelplatz?',
    all: [['spot', 'angelplatz', 'angelstelle', 'hotspot', 'stelle$', 'stellen$', 'platz', 'standplatz', 'angelplaetze'], ['find', 'such', 'erkenn', 'gut', 'wo', 'welch', 'best']],
    answer: 'Gute Plätze bieten Fischen drei Dinge: Deckung, Nahrung und Sauerstoff. Such deshalb nach Strukturen und Übergängen: Kanten, an denen das flache Wasser ins Tiefe abfällt, Krautkanten, Seerosenfelder, Schilfgürtel, versunkene Bäume, Steinpackungen, Stege, Einläufe und Zuflüsse. Im Fluss sind Strömungskanten, Kehrwasser hinter Hindernissen und Buhnenfelder top. Achte auf Zeichen wie jagende Fische, Vögel, die ins Wasser stoßen, oder Blasen. Deine eigenen Plätze kannst du auf der Karte speichern und mit Notizen ergänzen.',
    page: 'Map',
  },
  {
    id: 'see',
    category: 'gewaesser',
    question: 'Wie befische ich einen See?',
    all: [['see$', 'seen$', 'seeufer', 'baggersee', 'teich', 'stillwasser', 'weiher', 'talsperre']],
    any: ['wie', 'befisch', 'angel', 'wo', 'tipp', 'stell'],
    answer: 'An einem See suchst du zuerst die Strukturen: Einläufe, Landzungen, Buchten, Kanten, Plateaus und Krautfelder. Lote oder nutze ein Echolot, um herauszufinden, wo das Wasser vom Flachen ins Tiefe abfällt — an diesen Kanten ziehen die Fische entlang. Die windzugewandte Seite ist oft die fängigste, weil Nahrung dorthin getrieben wird. Im Sommer lohnt nachts das Flachwasser, tagsüber die Tiefe, im Winter die tiefsten Bereiche. Fisch systematisch und wechsle nach einer Weile ohne Kontakt den Platz.',
  },
  {
    id: 'fluss',
    category: 'gewaesser',
    question: 'Wie angle ich im Fluss?',
    all: [['fluss', 'fluesse', 'stroemung', 'bach', 'kanal', 'buhne', 'strom$']],
    any: ['wie', 'angel', 'wo', 'tipp', 'befisch', 'stell'],
    answer: 'Im Fluss stehen die Fische selten in der vollen Strömung, sondern dort, wo sie Kraft sparen und Nahrung vorbeitreibt: hinter Steinen und Brückenpfeilern, in Kehrwassern, an Strömungskanten, in Buhnenfeldern und Außenkurven mit tiefem Wasser. Wirf schräg stromauf und lass Köder oder Montage mit der Strömung treiben, so wirkt die Präsentation natürlich. Du brauchst meist schwerere Bleie oder Jigköpfe als im Stillwasser. Nach Regen und bei steigendem Pegel sind Aal und Döbel oft besonders aktiv, bei Hochwasser such die ruhigen Randbereiche.',
  },
  {
    id: 'struktur-kanten',
    category: 'gewaesser',
    question: 'Warum sind Kanten und Kraut so wichtig?',
    all: [['kante', 'abbruchkante', 'uferkante', 'krautkante', 'kraut', 'seerosen', 'schilf', 'struktur']],
    answer: 'An Kanten und Strukturen treffen sich Nahrung, Deckung und unterschiedliche Tiefen, deshalb sind sie die Hotspots im Gewässer. Raubfische lauern an Krautkanten, Schilfgürteln und versunkenen Bäumen auf Beute; Friedfische finden im Kraut Insektenlarven und Schnecken. An Abbruchkanten ziehen Fische wie auf einer Straße entlang. Fisch deshalb parallel zur Kante oder an der Grenze zum Kraut entlang, statt mitten ins Freiwasser zu werfen. Im dichten Kraut helfen krautfreie Montagen wie das Texas-Rig.',
  },

  // ------------------------------------------------------- Fischbehandlung
  {
    id: 'fisch-toeten',
    category: 'handling',
    question: 'Wie töte ich einen Fisch waidgerecht?',
    all: [['toet', 'betaeub', 'schlachten', 'waidgerecht', 'herzstich', 'fischtoeter', 'abschlagen']],
    answer: 'Willst du einen maßigen Fisch mitnehmen, musst du ihn nach dem Tierschutzrecht sofort betäuben und töten: 1. Fisch mit einem nassen Tuch festhalten. 2. Mit einem kräftigen Schlag mit dem Fischtöter auf den Hinterkopf, direkt über den Augen, betäuben. 3. Unmittelbar danach durch Herzstich oder Kiemenrundschnitt töten. 4. Den Fisch ausbluten lassen und sofort kühlen. Für Aale gelten besondere Vorgaben. Fische niemals lebend in Setzkescher oder Eimer aufbewahren, wenn das nicht ausdrücklich erlaubt ist.',
  },
  {
    id: 'haken-loesen',
    category: 'handling',
    question: 'Wie löse ich den Haken schonend?',
    all: [['haken', 'abhaken', 'verschluckt', 'geschluckt', 'loesezange'], ['loes', 'raus', 'entfern', 'abhaken', 'verschluckt', 'geschluckt', 'hakenloeser', 'loesezange', 'schonend']],
    answer: 'So gehst du schonend vor: Fisch möglichst im Wasser oder auf einer nassen Abhakmatte versorgen und nur mit nassen Händen anfassen, damit die Schleimhaut intakt bleibt. Mit Hakenlöser oder Lösezange den Haken in Gegenrichtung zum Einstich herausdrehen, beim Hecht mit Handschuh und Kiemengriff. Sitzt der Haken tief im Schlund eines Fisches, den du zurücksetzen musst, schneide das Vorfach möglichst nah am Haken ab, statt lange zu reißen. Schonender ist es, Schlucken zu vermeiden: früher anschlagen und größere Köder verwenden. Schonhaken ohne Widerhaken erleichtern das Lösen.',
  },
  {
    id: 'fisch-lagern',
    category: 'handling',
    question: 'Wie halte ich meinen Fang frisch?',
    all: [['frisch', 'kuehlen', 'kuehlbox', 'kuehlschrank', 'lagern', 'lagerung', 'aufbewahr', 'transport', 'einfrieren', 'haltbar', 'haelt sich'], ['fisch', 'fang', 'filet', 'hecht', 'zander', 'forelle', 'karpf', 'barsch', 'aal$', 'aale$']],
    any: ['halt', 'lange', 'kuehl'],
    answer: 'Nach dem waidgerechten Töten gilt: ausbluten lassen, ausnehmen und so schnell wie möglich kühlen, am besten in einer Kühlbox mit Kühlakkus oder Eis, nicht direkt in der Sonne. Ausgenommene Fische halten sich im Kühlschrank etwa zwei Tage. Zum Einfrieren gut abtrocknen, portionieren und luftdicht verpacken; magere Fische wie Zander oder Hecht halten sich so mehrere Monate, fette wie Aal oder Karpfen etwas kürzer. Auf Frische prüfst du an klaren Augen, roten Kiemen und festem Fleisch.',
  },
  {
    id: 'fisch-zubereiten',
    category: 'handling',
    question: 'Wie bereite ich meinen Fisch zu?',
    all: [['rezept', 'zubereit', 'bereite ich', 'raeucher', 'filetier', 'ausnehm', 'entschupp', 'schuppen$', 'fisch braten', 'fisch grillen', 'fischfilet']],
    any: ['fisch', 'hecht', 'zander', 'karpfen', 'forelle', 'barsch', 'aal', 'wie'],
    answer: 'Zuerst schuppen (Barsch, Karpfen) oder abziehen, dann ausnehmen: Bauch von der Afteröffnung bis zu den Kiemen aufschneiden, Innereien und die dunkle Niere an der Wirbelsäule entfernen, gut ausspülen. Forellen sind ganz gebraten oder geräuchert ein Klassiker, Zander- und Barschfilets gelingen kurz auf der Haut gebraten, Hecht eignet sich wegen der Gräten gut für Frikadellen oder in Streifen geschnitten. Unter Fischrezepte findest du passende Rezepte zu deinem Fang, von Braten bis Räuchern.',
    page: 'FishRecipes',
  },

  // --------------------------------------------------------------- Sicherheit
  {
    id: 'sicherheit',
    category: 'sicherheit',
    question: 'Worauf muss ich beim Angeln für meine Sicherheit achten?',
    all: [['sicherheit', 'sicher angeln', 'gefahr', 'schwimmweste', 'rettungsweste', 'unfall', 'ertrinken']],
    answer: 'Die wichtigsten Regeln: Auf dem Boot immer eine Schwimmweste tragen, auch als guter Schwimmer. Sag jemandem, wo du angelst und wann du zurück sein willst, besonders nachts oder allein. Prüf vorher das Wetter und brich bei Gewitter sofort ab. Achte auf rutschige und unterspülte Ufer, halte Abstand zu Stromleitungen beim Werfen, und geh nie auf Eis, dessen Tragfähigkeit du nicht sicher kennst. Ein Handy mit vollem Akku, eine Stirnlampe und ein kleines Erste-Hilfe-Set gehören immer in die Tasche.',
  },
  {
    id: 'eisangeln',
    category: 'sicherheit',
    question: 'Ist Eisangeln erlaubt und sicher?',
    all: [['eisangeln', 'auf dem eis', 'eisloch', 'eisdecke', 'zugefroren']],
    any: ['sicher', 'dick', 'gefahr'],
    answer: 'Eisangeln ist in Deutschland vielerorts verboten oder durch die Gewässerordnung eingeschränkt, also prüf das zuerst. Wo es erlaubt ist, gilt: Klares Eis sollte mindestens 10–15 cm dick sein, fließende Gewässer, Schilfzonen, Einläufe und Stellen mit Strömung frierst du nie sicher zu. Geh nie allein, trag Eispickel, Seil und Schwimmweste und prüf die Dicke regelmäßig mit dem Eisbohrer. Knackt oder dunkelt das Eis, sofort flach hinlegen und in der eigenen Spur zurückrobben.',
  },

  // ------------------------------------------------------ Wenn es nicht läuft
  {
    id: 'keine-bisse',
    category: 'probleme',
    question: 'Was tun, wenn nichts beißt?',
    all: [['beiss', 'biss', 'fange', 'faengt', 'fang', 'laeuft', 'zupft'], ['nicht', 'kein', 'nichts', 'schlecht', 'nie$', 'wenig']],
    any: ['falsch', 'tun', 'woran'],
    answer: 'Das passiert selbst Profis — so gehst du systematisch vor: 1. Tiefe ändern, denn oft stehen die Fische höher oder tiefer als gedacht. 2. Platz wechseln: Nach 20–30 Minuten ohne Kontakt beim Spinnfischen weiterziehen, an Kanten und Strukturen. 3. Tempo und Ködergröße anpassen, bei Kälte oder Hochdruck kleiner und langsamer. 4. Montage verfeinern: dünneres Vorfach, kleinerer Haken. 5. Zeit prüfen: Die Dämmerung ist fast immer besser als die Mittagshitze. 6. Leise sein und Abstand zum Ufer halten. Notier dir, was funktioniert — im Fangbuch erkennst du mit der Zeit deine Muster.',
  },
  {
    id: 'nur-kleine-fische',
    category: 'probleme',
    question: 'Warum fange ich nur kleine Fische?',
    all: [['kleine fische', 'nur kleine', 'zu klein', 'untermassig', 'kleinfisch', 'nur mini']],
    answer: 'Kleine Fische sind schneller und zahlreicher, sie sind oft vor den großen am Köder. Selektieren kannst du so: größere oder härtere Köder (Boilies statt Made, 12-cm- statt 5-cm-Gummifisch), größerer Haken, anderer Platz mit mehr Tiefe und Struktur, andere Tageszeit (große Fische jagen oft in Dämmerung und Nacht) und weniger feines Futter, das nur Kleinfische anlockt. Und Geduld: Große Fische sind seltener, deshalb bleiben erfolgreiche Angler länger an guten Plätzen.',
  },
  {
    id: 'grosse-fische',
    category: 'probleme',
    question: 'Wie fange ich große Fische?',
    all: [['grosse fische', 'grosser fisch', 'grossfisch', 'kapital', 'trophae', 'dicke fische', 'riesen', 'rekordfisch']],
    answer: 'Große Fische sind vorsichtig und fressen selektiv. Setz auf größere Köder, die kleine Fische nicht bewältigen, und fische dort, wo große Räuber Deckung und Nahrung finden: tiefe Kanten, große Strukturen, ruhige Randbereiche. Die besten Chancen hast du in der Dämmerung, nachts und im Herbst. Stell dein Gerät darauf ein (kräftigere Schnur, gut eingestellte Bremse, großer Kescher), damit der Fisch des Jahres nicht im Drill verloren geht. Und bleib an vielversprechenden Plätzen dran, statt ständig zu wechseln.',
  },
];
